apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-deployment
spec:
  selector:
    matchLabels:
      app: hello
      svc-type: lb
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        svc-type: lb
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
        env:
        - name: "PORT"
          value: "50000"
